name: budgi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.9.2

dependencies: 
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  get: 4.7.3
  firebase_core: 4.4.0
  convex_bottom_bar: 3.2.0
  syncfusion_flutter_datepicker: 32.2.8
  google_sign_in: 6.2.1
  firebase_auth: 6.1.4
  cloud_firestore: 6.1.2
  flutter_facebook_auth: 7.1.5
  intl_phone_number_input_v2: 0.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

